package codegen

import (
	"fmt"
	"os/user"
	"time"
)

// GenerationHeader returns a comment block for the top of generated files.
// The command parameter identifies which morphic command created the file
// (e.g. "dump-data", "morphic", "merge", "squash", "convert").
// The prefix is the comment character(s) to use (e.g. "#" for .star and .jsonl).
func GenerationHeader(prefix, command string) string {
	username := currentUsername()
	timestamp := time.Now().Format("2006-01-02 15:04:05")

	return fmt.Sprintf("%s Generated by: morphic %s\n%s User: %s\n%s Date: %s\n",
		prefix, command,
		prefix, username,
		prefix, timestamp)
}

// currentUsername returns the current OS username, or "unknown" on error.
func currentUsername() string {
	u, err := user.Current()
	if err != nil {
		return "unknown"
	}

	if u.Name != "" {
		return u.Name
	}

	return u.Username
}
