/*
MIT License

# Copyright (c) 2025 OcomSoft

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
package cmd

import (
	"github.com/spf13/cobra"

	"github.com/ocomsoft/morphic/internal/workflow"
	yamlpkg "github.com/ocomsoft/morphic/internal/yaml"
)

var (
	databaseType string
	pending      bool
)

// dumpSQLCmd represents the schema-to-sql command
var dumpSQLCmd = &cobra.Command{
	Use:     "schema-to-sql",
	Aliases: []string{"dump-sql", "dump_sql"},
	GroupID: "inspect",
	Short:   "Convert merged schema to SQL and print to console",
	Long: `Convert the merged schema to SQL and print to the console.

Without --pending: Dumps the complete merged schema as CREATE TABLE statements.
With --pending: Shows only the SQL that would be generated by the next migration
(ALTER TABLE, ADD COLUMN, DROP TABLE, etc.) based on changes between the current
schema and the last applied migration state.

This command scans all schema files in Go module dependencies and merges them
into a unified schema. In full mode, it outputs the complete SQL. In pending mode,
it diffs the current schema against the state from existing migrations and outputs
only the SQL for the detected changes.

Database Support:
- PostgreSQL (default)
- MySQL
- SQL Server
- SQLite`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return runDumpSQL(cmd, args)
	},
}

// runDumpSQL executes the dump_sql command
func runDumpSQL(cmd *cobra.Command, args []string) error {
	dagQuerier := &workflow.DAGQuerier{
		QueryPreviousSchema: func(migrationsDir string, dbType string, verbose bool) (*yamlpkg.Schema, error) {
			dagOut, err := queryDAG(migrationsDir, verbose)
			if err != nil {
				return nil, err
			}
			return schemaStateToYAMLSchema(dagOut.SchemaState, dbType), nil
		},
	}
	return workflow.ExecuteDumpSQL(cmd, databaseType, pending, verbose, cfgFile, dagQuerier)
}

func init() {
	rootCmd.AddCommand(dumpSQLCmd)

	// Add flags
	dumpSQLCmd.Flags().StringVar(&databaseType, "database", "postgresql",
		"Target database type (postgresql, mysql, sqlserver, sqlite)")
	dumpSQLCmd.Flags().BoolVar(&pending, "pending", false,
		"Show SQL for pending schema changes only (requires existing migrations)")
	dumpSQLCmd.Flags().BoolVar(&verbose, "verbose", false,
		"Show detailed processing information")
}
