// Code generated by 'yaegi extract github.com/ocomsoft/morphic/migrate'. DO NOT EDIT.

package symbols

import (
	"github.com/ocomsoft/morphic/internal/providers"
	"github.com/ocomsoft/morphic/migrate"
	"reflect"
)

func init() {
	Symbols["github.com/ocomsoft/morphic/migrate/migrate"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BuildGraph":            reflect.ValueOf(migrate.BuildGraph),
		"BuildProviderFromType": reflect.ValueOf(migrate.BuildProviderFromType),
		"EnvOr":                 reflect.ValueOf(migrate.EnvOr),
		"FormatLiteral":         reflect.ValueOf(migrate.FormatLiteral),
		"GlobalRegistry":        reflect.ValueOf(migrate.GlobalRegistry),
		"NewApp":                reflect.ValueOf(migrate.NewApp),
		"NewAppWithRegistry":    reflect.ValueOf(migrate.NewAppWithRegistry),
		"NewMigrationRecorder":  reflect.ValueOf(migrate.NewMigrationRecorder),
		"NewRegistry":           reflect.ValueOf(migrate.NewRegistry),
		"NewRunner":             reflect.ValueOf(migrate.NewRunner),
		"NewSchemaState":        reflect.ValueOf(migrate.NewSchemaState),
		"ReadJSONL":             reflect.ValueOf(migrate.ReadJSONL),
		"Register":              reflect.ValueOf(migrate.Register),
		"RenderDAGASCII":        reflect.ValueOf(migrate.RenderDAGASCII),
		"SortedKeys":            reflect.ValueOf(migrate.SortedKeys),
		"WriteJSONL":            reflect.ValueOf(migrate.WriteJSONL),

		// type definitions
		"AddField":             reflect.ValueOf((*migrate.AddField)(nil)),
		"AddForeignKey":        reflect.ValueOf((*migrate.AddForeignKey)(nil)),
		"AddIndex":             reflect.ValueOf((*migrate.AddIndex)(nil)),
		"AlterField":           reflect.ValueOf((*migrate.AlterField)(nil)),
		"App":                  reflect.ValueOf((*migrate.App)(nil)),
		"Config":               reflect.ValueOf((*migrate.Config)(nil)),
		"CreateTable":          reflect.ValueOf((*migrate.CreateTable)(nil)),
		"DAGOutput":            reflect.ValueOf((*migrate.DAGOutput)(nil)),
		"DefaultRef":           reflect.ValueOf((*migrate.DefaultRef)(nil)),
		"DropField":            reflect.ValueOf((*migrate.DropField)(nil)),
		"DropForeignKey":       reflect.ValueOf((*migrate.DropForeignKey)(nil)),
		"DropIndex":            reflect.ValueOf((*migrate.DropIndex)(nil)),
		"DropTable":            reflect.ValueOf((*migrate.DropTable)(nil)),
		"Field":                reflect.ValueOf((*migrate.Field)(nil)),
		"ForeignKey":           reflect.ValueOf((*migrate.ForeignKey)(nil)),
		"ForeignKeyConstraint": reflect.ValueOf((*migrate.ForeignKeyConstraint)(nil)),
		"Graph":                reflect.ValueOf((*migrate.Graph)(nil)),
		"Index":                reflect.ValueOf((*migrate.Index)(nil)),
		"ManyToMany":           reflect.ValueOf((*migrate.ManyToMany)(nil)),
		"Migration":            reflect.ValueOf((*migrate.Migration)(nil)),
		"MigrationRecorder":    reflect.ValueOf((*migrate.MigrationRecorder)(nil)),
		"MigrationSummary":     reflect.ValueOf((*migrate.MigrationSummary)(nil)),
		"Operation":            reflect.ValueOf((*migrate.Operation)(nil)),
		"OperationSummary":     reflect.ValueOf((*migrate.OperationSummary)(nil)),
		"Registry":             reflect.ValueOf((*migrate.Registry)(nil)),
		"RenameField":          reflect.ValueOf((*migrate.RenameField)(nil)),
		"RenameTable":          reflect.ValueOf((*migrate.RenameTable)(nil)),
		"RunOptions":           reflect.ValueOf((*migrate.RunOptions)(nil)),
		"RunSQL":               reflect.ValueOf((*migrate.RunSQL)(nil)),
		"Runner":               reflect.ValueOf((*migrate.Runner)(nil)),
		"SchemaState":          reflect.ValueOf((*migrate.SchemaState)(nil)),
		"SetDefaults":          reflect.ValueOf((*migrate.SetDefaults)(nil)),
		"SetTypeMappings":      reflect.ValueOf((*migrate.SetTypeMappings)(nil)),
		"TableState":           reflect.ValueOf((*migrate.TableState)(nil)),
		"UpsertData":           reflect.ValueOf((*migrate.UpsertData)(nil)),

		// interface wrapper definitions
		"_DataFileResolver": reflect.ValueOf((*_github_com_ocomsoft_morphic_migrate_DataFileResolver)(nil)),
		"_Operation":        reflect.ValueOf((*_github_com_ocomsoft_morphic_migrate_Operation)(nil)),
	}
}

// _github_com_ocomsoft_morphic_migrate_DataFileResolver is an interface wrapper for DataFileResolver type
type _github_com_ocomsoft_morphic_migrate_DataFileResolver struct {
	IValue       interface{}
	WSetBasePath func(dir string)
}

func (W _github_com_ocomsoft_morphic_migrate_DataFileResolver) SetBasePath(dir string) {
	W.WSetBasePath(dir)
}

// _github_com_ocomsoft_morphic_migrate_Operation is an interface wrapper for Operation type
type _github_com_ocomsoft_morphic_migrate_Operation struct {
	IValue         interface{}
	WDescribe      func() string
	WDown          func(p providers.Provider, state *migrate.SchemaState, defaults map[string]string) (string, error)
	WIsDestructive func() bool
	WMutate        func(state *migrate.SchemaState) error
	WTableName     func() string
	WTypeName      func() string
	WUp            func(p providers.Provider, state *migrate.SchemaState, defaults map[string]string) (string, error)
}

func (W _github_com_ocomsoft_morphic_migrate_Operation) Describe() string {
	return W.WDescribe()
}
func (W _github_com_ocomsoft_morphic_migrate_Operation) Down(p providers.Provider, state *migrate.SchemaState, defaults map[string]string) (string, error) {
	return W.WDown(p, state, defaults)
}
func (W _github_com_ocomsoft_morphic_migrate_Operation) IsDestructive() bool {
	return W.WIsDestructive()
}
func (W _github_com_ocomsoft_morphic_migrate_Operation) Mutate(state *migrate.SchemaState) error {
	return W.WMutate(state)
}
func (W _github_com_ocomsoft_morphic_migrate_Operation) TableName() string {
	return W.WTableName()
}
func (W _github_com_ocomsoft_morphic_migrate_Operation) TypeName() string {
	return W.WTypeName()
}
func (W _github_com_ocomsoft_morphic_migrate_Operation) Up(p providers.Provider, state *migrate.SchemaState, defaults map[string]string) (string, error) {
	return W.WUp(p, state, defaults)
}
